// Generated by Wrangler by running `wrangler types --experimental-include-runtime`

interface Env {
	KVDO: DurableObjectNamespace<import("./src/index").PerfKVDO>;
	PerfDOKV: AnalyticsEngineDataset;
}
