name = "action-delay-api-workers-ai"
main = "src/index.ts"
compatibility_date = "2024-12-29"


[ai]
binding = "AI"

# wrangler.toml (wrangler v3.88.0^)
[observability.logs]
enabled = true



[[analytics_engine_datasets]]
binding = "AE"
dataset = "AI"




