name = "action-delay-api-perf-do-kv"
main = "src/index.ts"
compatibility_date = "2024-09-12"
logpush = true
account_id = "b9e510810e1e12fcd40826d266a1fb12"
workers_dev = true





analytics_engine_datasets = [
    { binding = "PerfDOKV" }
]



[durable_objects]
bindings = [{name = "KVDO", class_name = "PerfKVDO"}]



[observability]
enabled = true



[[migrations]]
tag = "v1" # Should be unique for each entry
new_classes = ["PerfKVDO"]