# fly.toml app configuration file generated for action-delay-api-perf on 2025-01-12T22:08:18-05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'action-delay-api-perf'
primary_region = 'iad'


[build]
  image = "ghcr.io/tyler-obrien/action-delay-api-perf-simpleaspnetapi:latest"


[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 1
  processes = ['app']




[[http_service.checks]]
  grace_period = "10s"
  interval = "30s"
  method = "GET"
  timeout = "5s"
  path = "/helloworld"


[[vm]]
  size = 'shared-cpu-1x'
