name = "action-delay-api-worker-assets-isolated-test"
main = "src/index.ts"
compatibility_date = "2025-04-01"


[assets]
directory = "./public"
binding= "ASSETS"
not_found_handling = "404-page"



[observability]
enabled = true
head_sampling_rate = 1